### ISSUE TITLE
Ubuntuでの動作

### ISSUE THREAD

**Issue by tkgstrator** [murosan/shogi-proxy-server#1]
Ubuntu上でやねうら王系エンジンをビルドし、Webサーバを立ち上げてshogi-board及びshogi-board-serverを動かしてみたところ、エンジンを認識するところまで至ったのですが選択したときにタイムアウトで落ちてしまいました。

以下が、そのときにサーバ側に表示されたログになります。

```bash
{"level":"error","time":"2020-02-18T05:28:36.490Z","caller":"engine/engine.go:253","msg":"[waitFor] timed out","error":"Execution timed out","errorVerbose":"Execution timed out\ngithub.com/murosan/shogi-board-server/app/domain/model/exception.init\n\t/home/ubuntu/go/src/github.com/murosan/shogi-board-server/app/domain/model/exception/errors.go:13\ngithub.com/murosan/shogi-board-server/app/domain/entity/engine.init\n\t<autogenerated>:1\ngithub.com/murosan/shogi-board-server/app/server/controllers.init\n\t<autogenerated>:1\nmain.init\n\t<autogenerated>:1\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:189\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1333","stacktrace":"github.com/murosan/shogi-board-server/app/domain/entity/engine.(*Engine).waitFor\n\t/home/ubuntu/go/src/github.com/murosan/shogi-board-server/app/domain/entity/engine/engine.go:253\ngithub.com/murosan/shogi-board-server/app/domain/entity/engine.New\n\t/home/ubuntu/go/src/github.com/murosan/shogi-board-server/app/domain/entity/engine/engine.go:106\ngithub.com/murosan/shogi-board-server/app/server/controllers.Connect.func1\n\t/home/ubuntu/go/src/github.com/murosan/shogi-board-server/app/server/controllers/connect.go:53\ngithub.com/labstack/echo.(*Echo).add.func1\n\t/home/ubuntu/go/src/github.com/labstack/echo/echo.go:511\ngithub.com/labstack/echo/middleware.CORSWithConfig.func1.1\n\t/home/ubuntu/go/src/github.com/labstack/echo/middleware/cors.go:121\ngithub.com/labstack/echo/middleware.RecoverWithConfig.func1.1\n\t/home/ubuntu/go/src/github.com/labstack/echo/middleware/recover.go:78\ngithub.com/labstack/echo/middleware.LoggerWithConfig.func2.1\n\t/home/ubuntu/go/src/github.com/labstack/echo/middleware/logger.go:117\ngithub.com/labstack/echo.(*Echo).ServeHTTP\n\t/home/ubuntu/go/src/github.com/labstack/echo/echo.go:622\nnet/http.serverHandler.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2741\nnet/http.(*conn).serve\n\t/usr/local/go/src/net/http/server.go:1847"}
{"level":"error","time":"2020-02-18T05:28:36.491Z","caller":"controllers/connect.go:56","msg":"[Connect] initialize Engine","error":"could not get 'readyok' from the engine: Execution timed out","errorVerbose":"Execution timed out\ngithub.com/murosan/shogi-board-server/app/domain/model/exception.init\n\t/home/ubuntu/go/src/github.com/murosan/shogi-board-server/app/domain/model/exception/errors.go:13\ngithub.com/murosan/shogi-board-server/app/domain/entity/engine.init\n\t<autogenerated>:1\ngithub.com/murosan/shogi-board-server/app/server/controllers.init\n\t<autogenerated>:1\nmain.init\n\t<autogenerated>:1\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:189\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1333\ncould not get 'readyok' from the engine\ngithub.com/murosan/shogi-board-server/app/domain/entity/engine.New\n\t/home/ubuntu/go/src/github.com/murosan/shogi-board-server/app/domain/entity/engine/engine.go:107\ngithub.com/murosan/shogi-board-server/app/server/controllers.Connect.func1\n\t/home/ubuntu/go/src/github.com/murosan/shogi-board-server/app/server/controllers/connect.go:53\ngithub.com/labstack/echo.(*Echo).add.func1\n\t/home/ubuntu/go/src/github.com/labstack/echo/echo.go:511\ngithub.com/labstack/echo/middleware.CORSWithConfig.func1.1\n\t/home/ubuntu/go/src/github.com/labstack/echo/middleware/cors.go:121\ngithub.com/labstack/echo/middleware.RecoverWithConfig.func1.1\n\t/home/ubuntu/go/src/github.com/labstack/echo/middleware/recover.go:78\ngithub.com/labstack/echo/middleware.LoggerWithConfig.func2.1\n\t/home/ubuntu/go/src/github.com/labstack/echo/middleware/logger.go:117\ngithub.com/labstack/echo.(*Echo).ServeHTTP\n\t/home/ubuntu/go/src/github.com/labstack/echo/echo.go:622\nnet/http.serverHandler.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2741\nnet/http.(*conn).serve\n\t/usr/local/go/src/net/http/server.go:1847\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1333","stacktrace":"github.com/murosan/shogi-board-server/app/server/controllers.Connect.func1\n\t/home/ubuntu/go/src/github.com/murosan/shogi-board-server/app/server/controllers/connect.go:56\ngithub.com/labstack/echo.(*Echo).add.func1\n\t/home/ubuntu/go/src/github.com/labstack/echo/echo.go:511\ngithub.com/labstack/echo/middleware.CORSWithConfig.func1.1\n\t/home/ubuntu/go/src/github.com/labstack/echo/middleware/cors.go:121\ngithub.com/labstack/echo/middleware.RecoverWithConfig.func1.1\n\t/home/ubuntu/go/src/github.com/labstack/echo/middleware/recover.go:78\ngithub.com/labstack/echo/middleware.LoggerWithConfig.func2.1\n\t/home/ubuntu/go/src/github.com/labstack/echo/middleware/logger.go:117\ngithub.com/labstack/echo.(*Echo).ServeHTTP\n\t/home/ubuntu/go/src/github.com/labstack/echo/echo.go:622\nnet/http.serverHandler.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2741\nnet/http.(*conn).serve\n\t/usr/local/go/src/net/http/server.go:1847"}
```

ローカルでは動いているのでやねうら王側の問題ではないと思います。

## 環境
OS: Ubuntu 18.04
思考エンジン: [dolphin+illqha](https://drive.google.com/file/d/1ST_XNioYuVqt9wOh7SCVIELY3OKRikGf/view)
評価関数 : [orqha2018](https://www.qhapaq.org/shogi/kifdb/)

**Comment by murosan** [comment]
ubuntu 上でやねうら王を直接立ち上げて、`usi` コマンドと `isready` コマンドを試していただけますか？
`usi` は `usiok`、
`isready` は `readyok` が返されるはずです。

そのときの出力内容と、エンジン側から出力が返るまでにどのぐらい時間がかかるか、を教えていただきたいです :pray:

---

```
could not get 'readyok' from the engine: Execution timed out
```
と出ているので、もしかしたら readyok の応答に shogi-board-server の設定値以上の時間がかかってしまっているのかもしれません。
その場合は対応します :bow:

**Comment by tkgstrator** [comment]
```bash
ubuntu@ip-172-31-29-245:~/shogi-board-server/engines$ ./illqha 
usi
id name YaneuraOu 2018 T.N.K. (dolphin) NNUE 4.82 64AVX2
id author by yaneurao
option name Threads type spin default 4 min 1 max 512
option name Hash type spin default 16 min 1 max 1048576
option name MultiPV type spin default 1 min 1 max 800
option name WriteDebugLog type check default false
option name NetworkDelay type spin default 120 min 0 max 10000
option name NetworkDelay2 type spin default 1120 min 0 max 10000
option name MinimumThinkingTime type spin default 2000 min 1000 max 100000
option name SlowMover type spin default 100 min 1 max 1000
option name MaxMovesToDraw type spin default 0 min 0 max 100000
option name DepthLimit type spin default 0 min 0 max 2147483647
option name NodesLimit type spin default 0 min 0 max 9223372036854775807
option name Contempt type spin default 2 min -30000 max 30000
option name ContemptFromBlack type check default false
option name EnteringKingRule type combo default CSARule27 var NoEnteringKing var CSARule24 var CSARule27 var TryRule
option name EvalDir type string default eval
option name SkipLoadingEval type check default false
option name NarrowBook type check default false
option name BookMoves type spin default 16 min 0 max 10000
option name BookIgnoreRate type spin default 0 min 0 max 100
option name BookFile type combo default standard_book.db var no_book var standard_book.db var yaneura_book1.db var yaneura_book2.db var yaneura_book3.db var yaneura_book4.db var user_book1.db var user_book2.db var user_book3.db var book.bin
option name BookEvalDiff type spin default 30 min 0 max 99999
option name BookEvalBlackLimit type spin default 0 min -99999 max 99999
option name BookEvalWhiteLimit type spin default -140 min -99999 max 99999
option name BookDepthLimit type spin default 16 min 0 max 99999
option name BookOnTheFly type check default false
option name ConsiderBookMoveCount type check default false
option name PvInterval type spin default 300 min 0 max 100000
option name ResignValue type spin default 99999 min 0 max 99999
option name nodestime type spin default 0 min 0 max 99999
option name Param1 type spin default 0 min 0 max 100000
option name Param2 type spin default 0 min 0 max 100000
option name EvalSaveDir type string default evalsave
option name ConsiderationMode type check default false
option name OutputFailLHPV type check default true
usiok
isready
readyok
```

最初は自分もここの応答が時間がかかっているのかと思ったのですが、実際にはすぐに出力が返ってきました。60秒の思考も問題なくbestmoveが返ってきています。

**Comment by murosan** [comment]
ありがとうございます。確認します

**Comment by murosan** [comment]
エンジン側が相対パスで eval を読み込もうと試みるが、PWD が別ディレクトリのため、eval を読み込めていない可能性が高そうです。

一旦の解決策としては、

1. shogi-board-server とエンジンのバイナリを同じディレクトリに置いて実行する
2. エンジンバイナリが置いてあるディレクトリに移動してから shogi-board-server を起動する

といった手段が考えられそうです。

**Comment by murosan** [comment]
エンジン側が相対パスで解決しようとする以上、shogi-board-server 側での対処は難しいのですが、
オプション入力画面を表示する前に isready を流し込んでいるのは良くないので修正します。

**Comment by tkgstrator** [comment]
ご指摘の通りshogi-board-serverの実行ファイルを思考エンジンと同じところに配置したところ、正しくエンジンを認識することができました。ありがとうございました。

これはまた別件なのでここに書いて良いものかどうかわからないのですが、後手の駒の成・不成が上下逆さまに表示されているのと、移動先（例えば9九角成ですと、9九の位置に表示されるのでクリックしにくい）ではなくて常に中央に表示するようにすれば更に便利になるのではないかと思いました。

**Comment by murosan** [comment]
中央だと余計なマウス移動が発生して嫌だったので、移動先で表示するようにしています。
慣れると結構快適だとは思います。

後手で上下逆なのは迷ったところなのですが、最初逆じゃない表示にしていたら違和感があったので逆にしました。
例えば棋譜で、後手が「57銀上成」とした場合、`あがる`の方向は先手から見ると下側なので、そういった将棋の仕様にも合うように、後手の進む方向を `成` にしたかった、というのもあります。

**Comment by murosan** [comment]
それと今回の問題の根本解決なのですが、やはりやねうら側でパスの解決方法を改善してもらうしかないのかなと思っています。
例えばシェルスクリプトで eval ディレクトリのパスを表現する時に、以下のようにすると、別ディレクトリからコマンドが実行された場合に、正しく取得できません。
```sh
EVAL_DIR="./eval"
```

ちゃんとやるとこんな感じ

```sh
EVAL_DIR="$(dirname $0)/eval"
```

やねうら王のコードはまだ見ていないですが、同様のことはできるはず。

**Comment by tkgstrator** [comment]
> 移動先について

真ん中だと確かに余計なマウスカーソルの移動が必要でちょっと面倒かもしれないですね。ですが、やはり盤の中だけに表示だと狭くて誤クリックしそうなのでもう少し選択ダイアログが大きくてもいいかもしれません。また、せっかく駒を画像表示しているので例えば歩だったら「と」か「歩」で表示するのもありかもしれないですね（将棋ウォーズなどではこちらのスタイルを採用しています）

> 評価値表示について

評価値が常に「手番側から見て+なら有利、-なら不利」になっているのですが他の検討ソフトでもそうであるように、手番は考慮せずに「+なら先手有利、-なら後手有利」の方が他の検討ソフトの代替として利用しやすいのではないかと思いました。（設定から選択できるのであればよりベターかも知れません）

> 根本的解決

そうですね。おっしゃられるようにやねうら王側で常に思考エンジンの絶対パスを取得してから評価関数ファイルを参照するようにすればこの問題は解決できそうです。

長文失礼しました。

**Comment by murosan** [comment]
移動先のマス拡大は確かにやりたいかもしれないです。CSS でできるかどうか次第なので検討します :pray:

評価値はソフトから流れてくる数値をそのまま表示しているだけなのでこちらでコントロールするのは厳しいですね...。
ソフトによっても挙動が違いますし。
`手番は考慮せずに「+なら先手有利、-なら後手有利」`  これは自分もその通りだと思っていて、ただやっぱりこちら側での制御は難しいです。
ソフト製作者の意図はあると思うのでやねうら王側に issue を出しても良いかもしれません。

個人的には詰みで評価値が 0 になるのも、数値の意味が一意じゃないのであまり好きではないですw。

**Comment by tkgstrator** [comment]
評価値については「手番がblackだったらその値を表示して、whiteだったら反転させる」みたいな処理で見た目上は対応できそうな気もするのですが、可能でしょうか？

> 詰み判定時

これはUSIプロトコルを抜本から変えるしか解決策がなさそうですね..

**Comment by murosan** [comment]
見た目上だけ対応することは可能です。
仕様に詳しくないのですが、返る評価値の意味って全ソフト一緒ですか？

一緒であれば対応しても良いと思っています。

**Comment by tkgstrator** [comment]
評価値は確か歩一枚に対する価値を100点とした時の形勢判断だった気がします。
ただ、-1が返るときは千日手が最善手とかだったような...

**Comment by murosan** [comment]
あ、すみません、仮に後手番で評価値に -1 をかけるとすると、
元々 `「+なら先手有利、-なら後手有利」` という仕様にしているソフトがあると崩壊するなーと思った次第です。

その辺りの挙動が全てのソフトで統一されていれば問題ないです。

**Comment by tkgstrator** [comment]
現在のUSIプロトコル準拠の思考エンジンであれば全部統一されているはずなので（そうでないとShogiGUIでも表示がおかしくなってしまう）、多分大丈夫だと思います。
あと、これは完全に私用なのですが局面をSfen形式でクリップボードにコピーできる機能があるとものすごく便利です（笑）

**Comment by murosan** [comment]
なるほど。
であれば後手の時に -1 かけるのは対応します。

Sfen は...、すみませんが、すぐに対応する予定はないです

**Comment by tkgstrator** [comment]
> Sfen

なんと！！実はいろいろ書いた中で一番欲しかった機能なのですが...（泣）
コードをまだ読めていないのですが内部的にはSfenで局面管理されているのでしょうか？

もしそうなら自分でこっそり実装しておきます。

**Comment by murosan** [comment]
サーバー側で変換して渡しているのでフロントは sfen 持ってないですね。
sfen はサーバーのログにしかないです...。

ログは JSON で出してるので、ログから拾うことは可能ですかね、一応。
https://github.com/murosan/shogi-board-server/blob/master/app/server/controllers/position.go#L45
`[SetPosition]`  で grep すれば取れるといえば取れるかも。

**Comment by murosan** [comment]
https://github.com/murosan/shogi-board/commit/69f882a34d0786a883b8c15d9a2295b9e4904401
後手番での評価値の反転は実装完了しました。
playground にも反映済みです。

**Comment by tkgstrator** [comment]
ありがとうございます。

評価値反転機能を反映させようとしたのですが、最新のコミットにしてから`docker-compose build`とするとnodeとyarnのところでエラーがでてしまいました。

```bash
[1/5] Validating package.json...
error shogi-board@3.1.0: The engine "node" is incompatible with this module. Expected version ">=13.5.0". Got "10.19.0"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
ERROR: Service 'front' failed to build: The command '/bin/sh -c yarn --pure-lockfile' returned a non-zero code: 1
```

**Comment by murosan** [comment]
Docker image の Node.js のバージョンアップを忘れていたので、上げました。

**Comment by tkgstrator** [comment]
うちのAWSはカナダのものを使っているのですが、`docker-compose up`でshogi-boardを起動すると時刻のズレでlatencyの値がとんでもない数字になって固まってしまいます。
TZがAsia/Tokyoで決め打ちになっている？のが原因な気がします。

```bash
{"time":"2020-02-20T03:06:23.976705726Z","id":"","remote_ip":"99.230.171.132","host":"shogi.mydns.jp:8080","method":"POST","uri":"/connect?key=illqha","user_agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.106 Safari/537.36","status":200,"error":"","latency":999944419,"latency_human":"999.944419ms","bytes_in":0,"bytes_out":0}
{"level":"info","time":"2020-02-20T03:06:43.339Z","caller":"controllers/option.go:25","msg":"[GetOptions] param check","name":"illqha"}
```

**Comment by murosan** [comment]
うーん、そのログだけではなんとも...。

shogi-board → ローカル(Asia/Tokyo)
shogi-board-server → AWS(Canada/Newfoundland | Canada/Saskatchewan)
ということですか？

↓ を試してもう少し情報をいただけると

#### 対処法案

- ローカル → ローカル でうまくいくか試す
- ローカル → ローカル で Dockerfile のタイムゾーンを変更してみてうまくいくか試す
  (`docker-compose down --rmi all` してから up しなおす)

- https://murosan.github.io/shogi-board/playground/
  ここから試しても同じか試す

**Comment by tkgstrator** [comment]
> 情報不足

ですよね(´・ω・`)
一応どちらもカナダのAWS上で動いています。

どうもポート3000を使っているのがダメなような気がします。最新のリリースのやつをサーバに展開したときにはちゃんと動くので...。そこで自分でリリース用のファイルを作成しようと思うのですが、どういったコマンドで作成できるのでしょうか？`npm run-script build`じゃなかったのでわからなくて...すみません。

**Comment by murosan** [comment]
情報ありがとうございます。
コマンドは `yarn build` です。
https://github.com/murosan/shogi-board/blob/master/package.json#L66

Node.js とは別にダウンロードが必要です。
https://classic.yarnpkg.com/ja/

とりあえず手元でビルドしたものは以下です。一旦これで試していただけると :pray:
[shogi-board.zip](https://github.com/murosan/shogi-board-server/files/4228785/shogi-board.zip)

**Comment by tkgstrator** [comment]
> 手元でビルドしたもの

これをそのまま上書きするとエンジンがちゃんと読み込めました！ただ、評価値の反転が反映されていないようです。ひょっとするとChromeのキャッシュ問題かもしれないのでまたご報告させていただきます。

> 追記

キャッシュの強制リロードで想定通りの評価値表示ができました。

> おまけ

実は`yarn build`も試していたのですが、以下のエラーが表示されてビルドができませんでした。

```bash
yarn run v1.21.1
$ react-scripts build
/bin/sh: 1: react-scripts: not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by murosan** [comment]
先に `yarn install` or `yarn` でパッケージをインストールしてください。

あとすみません、↓ ここを
https://github.com/murosan/shogi-board/blob/master/package.json#L22
↓このように変更する必要があるかもしれません。
```json
"homepage": ".",
```

### 追記
homepage は、`PUBLIC_URL` を環境変数に設定する、でもいけるかも。

**Comment by murosan** [comment]
遅くなりましたが、
https://github.com/murosan/shogi-board-server/releases/tag/v1.1.0 にて、
オプション入力前に isready を実行していた問題を修正、
https://github.com/murosan/shogi-board-server/releases/tag/v1.2.0 にて、
現在局面を sfen で取得できる API を追加しました。
