### ISSUE TITLE
前回と同じ設定のはずなのにエンジンが認識されない

### ISSUE THREAD

**Issue by Kei-Toba** [murosan/shogi-proxy-server#6]
質問失礼します。
久しぶりにshogi-boardを触ってみたところエンジンが認識されませんでした。1年ほど前に使ってから設定は変えてません。
パスに記載されているエンジンを実行してreadyokと出たのも確認しています。

1. サーバーが起動しているか
2. サーバーのURLが正しいか
3. サーバーのログを確認し、エラー等が出ていないか
4. サーバーで将棋エンジンの実行パスを設定したか
5. 将棋エンジンが実行可能であるか

以上の件についてもしっかりと確認できているので、OSのアプデが原因なのではと思っているのですがどうでしょうか？

**Comment by Kei-Toba** [comment]
**追記**
ブラウザをSafariからChromeに変えたところ、将棋エンジンの一覧を読み込むことができました。
しかし、接続に失敗しましたと表示されてエンジンを使用することができませんでした。

> eval ディレクトリが読めてないことが原因の可能性があるので、一旦以下のいずれかの方法を試していただけますか？
> 
> 1. shogi-board-server とエンジンのバイナリを同じディレクトリに置いて実行する
> 2. エンジンバイナリが置いてあるディレクトリに移動してから shogi-board-server を起動する
> 3. eval を shogi-board-server と同じディレクトリに置いて実行する

上を参考にそれぞれ試してみましたが、解決には至りませんでした。
![スクリーンショット 2022-05-28 8 51 10](https://user-images.githubusercontent.com/60617580/170801210-17eebaac-2472-45cd-ae88-038f285a4195.png)

**Comment by murosan** [comment]
> OSのアプデが原因

その可能性はありそうですね

新しい実行ファイルを作りましたので、↓からダウンロードしてお試しください :pray:
https://github.com/murosan/shogi-board-server/releases/tag/v1.4.0

**Comment by Kei-Toba** [comment]
Safariだと相変わらず起動しなかったので、Chromeで試したところ以下のエラーが出ました。私側の不手際でしたらご指摘いただけると幸いです。（頼りっきりになってしまい申し訳ありません）
`{"level":"error","time":"2022-05-28T18:22:17.332+0900","caller":"service/engine_control.go:152","msg":"parse string","error":"failed to parse string. input = option name WriteDebugLog type string default \nFormats\n  Button:   option name <string> type button\n  Check:    option name <string> type check default <bool>\n  Spin:     option name <string> type spin default <int> min <int> max <int>\n  Select:   option name <string> type combo default <string> rep(var <string>)\n  Text:     option name <string> type string default <string>\n            option name <string> type filename default <string>\n","stacktrace":"github.com/murosan/shogi-board-server/app/domain/service.(*engineControlService).Connect.func1\n\t/Users/masashi/workspace/shogi/shogi-board-app/shogi-board-server/app/domain/service/engine_control.go:152\ngithub.com/murosan/shogi-board-server/app/domain/infrastructure.(*connector).OnReceive\n\t/Users/masashi/workspace/shogi/shogi-board-app/shogi-board-server/app/domain/infrastructure/connection.go:69"}
{"level":"info","time":"2022-05-28T18:22:17.332+0900","caller":"service/engine_control.go:154","msg":"parsed string","value":"<nil>"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x12d4d33]`

**Comment by murosan** [comment]
将棋エンジンから、
`option name WriteDebugLog type string default `
というオプションが渡されているようです。

[将棋所：USIプロトコルとは](http://shogidokoro.starfree.jp/usi.html) の option の説明欄に以下のように記載されており、shogi-board-server はその仕様に従っているため、WriteDebugLogオプションを読み込めなかった模様です。
> stringまたはfilenameでデフォルト値が空の文字列の場合は`<empty>`を指定して下さい。（emptyの両側に不等号の記号が必要です。）

**Comment by murosan** [comment]
`option name WriteDebugLog type string default <empty>`
のように出力されていれば読み込めるはずです

**Comment by Kei-Toba** [comment]
WriteDebugLogの値を`<empty>`に書き換えてみたのですがそれだとなぜか上手くいかなかったので、代わりに別の実行ファイル（
値が`option name WriteDebugLog type check default false`となっているもの）を使ったところ無事に動きました。
ご迷惑をおかけしてすみませんでした。迅速な対応をしていただいてとてもありがたかったです。

**Comment by murosan** [comment]
良かったです！
